services:
  - type: static
    name: slate-fox-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html